# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-content-pvc # Nombre del Persistent Volume Claim
  namespace: web-estatica
spec:
  storageClassName: manual 
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 100Mi # Cuánto almacenamiento solicita